---
- name: Install Libvirt and KVM
  apt: name={{ item }} update_cache=yes state=present cache_valid_time=3600
  with_items:
   - libvirt-bin
   - qemu-kvm
   - python-libvirt

- name: Configure Libvirtd daemon
  lineinfile: dest=/etc/libvirt/libvirtd.conf regexp="{{ item.regexp }}" line="{{ item.line }}" insertafter=EOF 
  with_items: 
   - line: 'listen_tls = 0'
     regexp: '^#?listen_tls'
   - line: 'listen_tcp = 1'
     regexp: '^#?listen_tcp'
   - line: 'tcp_port = \"16509\"'
     regexp: '^#?tcp_port'
   - line: 'auth_tcp = \"none\"'
     regexp: '^#?auth_tcp'
   - line: 'mdns_adv = 0'
     regexp: '^#?mdns_adv'

- name: Change Libvirtd options
  lineinfile: dest=/etc/default/libvirt-bin regexp='^libvirtd_opts="-d"' line='libvirtd_opts="-d -l"'

- name: Remove libvirtd AppArmor definition from the kernel
  shell: apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
  args:
    creates: /etc/apparmor.d/disable/usr.sbin.libvirtd

- name: Remove virt-aa-helper AppArmor definition from the kernel
  shell: apparmor_parser -R /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
  args:
    creates: /etc/apparmor.d/disable/usr.lib.libvirt.virt-aa-helper

- name: Disable AppArmor for libvirtd
  file: state=link src="/etc/apparmor.d/usr.sbin.libvirtd" path="/etc/apparmor.d/disable/usr.sbin.libvirtd"

- name: Disable AppArmor for virt-aa-helper
  file: state=link src="/etc/apparmor.d/usr.lib.libvirt.virt-aa-helper" path="/etc/apparmor.d/disable/usr.lib.libvirt.virt-aa-helper" force=yes

- name: Restart Libvirtd
  service: name=libvirt-bin state=restarted enabled=true

